import Foundation

struct GenerateTestsTool: MCPTool {
    let name = "generate_swift_tests"
    let description = "Generates XCTest unit test templates based on the public interface of a Swift file."
    
    func execute(input: [String: String]) async throws -> String {
        guard let filePath = input["file_path"] else {
            throw MCPToolError.missingParameter("file_path")
        }
        
        guard FileManager.default.fileExists(atPath: filePath) else {
            throw MCPToolError.fileNotFound(filePath)
        }
        
        let url = URL(fileURLWithPath: filePath)
        let content = try String(contentsOf: url, encoding: .utf8)
        let lines = content.components(separatedBy: .newlines)
        let fileName = url.deletingPathExtension().lastPathComponent
        
        // Extrae funciones públicas
        let publicFunctions = lines.filter {
            ($0.contains("func ") && !$0.contains("private ") && !$0.contains("//"))
        }
        
        // Extrae structs y clases
        let types = lines.filter {
            ($0.contains("struct ") || $0.contains("class ")) &&
            $0.contains("{") &&
            !$0.contains("//")
        }
        
        var testCode = """
        import XCTest
        @testable import SwiftBridgeMCP
        
        // Generated by SwiftBridge MCP — review before use
        final class \(fileName)Tests: XCTestCase {
        
        """
        
        // Genera un test por cada función encontrada
        for funcLine in publicFunctions.prefix(6) {
            let cleaned = funcLine.trimmingCharacters(in: .whitespaces)
            let funcName = extractFunctionName(from: cleaned)
            
            testCode += """
                func test_\(funcName)() throws {
                    // Arrange
                    // TODO: set up test data
                    
                    // Act
                    // TODO: call \(funcName)
                    
                    // Assert
                    // TODO: verify expected behavior
                    XCTFail("Test not implemented yet")
                }
            
            """
        }
        
        testCode += "}\n"
        
        var result = "🧪 GENERATED TEST TEMPLATE\n"
        result += "─────────────────────────────────\n"
        result += "Types found: \(types.count)\n"
        result += "Functions found: \(publicFunctions.count)\n"
        result += "Tests generated: \(min(publicFunctions.count, 6))\n\n"
        result += testCode
        
        return result
    }
    
    private func extractFunctionName(from line: String) -> String {
        guard let funcRange = line.range(of: "func ") else { return "unknown" }
        let afterFunc = String(line[funcRange.upperBound...])
        return afterFunc.components(separatedBy: CharacterSet(charactersIn: "( ")).first ?? "unknown"
    }
}
